[build]
  command = "npm run build"  # o el comando que uses para construir tu proyecto
  publish = "public"         # carpeta donde se publica tu sitio, ajústalo si es necesario

[build.environment]
  NODE_VERSION = "16"        # Cambia por la versión que uses

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]
